### ISSUE TITLE
atomic 1.1.12 does not work with jruby <= 1.7.2

### ISSUE THREAD

**Issue by splattael** [headius/ruby-atomic#28]
It seems that `atomic` version `1.1.12` does work with `jruby` <= `1.7.2`.

Example:

``` ruby
gem 'atomic', '1.1.12'
require 'atomic'
p :jruby => JRUBY_VERSION
p Atomic.new(0)
```
## jruby 1.7.3

```
{:jruby=>"1.7.3"}
#<Atomic:0xa2ba05>
```
## jruby 1.7.2

```
$ ruby foo.rb 
{:jruby=>"1.7.2"}
AtomicReferenceLibrary.java:70:in `<clinit>': java.lang.NoClassDefFoundError: org/jruby/util/unsafe/UnsafeHolder
    from AtomicReferenceLibrary.java:51:in `allocate'
    from RubyClass.java:224:in `allocate'
    from RubyClass.java:854:in `newInstance'
    from RubyClass$INVOKER$i$newInstance.gen:-1:in `call'
    from JavaMethod.java:278:in `call'
    from CachingCallSite.java:326:in `cacheAndCall'
    from CachingCallSite.java:170:in `call'
    from foo.rb:6:in `__file__'
    from foo.rb:-1:in `load'
    from Ruby.java:810:in `runScript'
    from Ruby.java:803:in `runScript'
    from Ruby.java:674:in `runNormally'
    from Ruby.java:523:in `runFromMain'
    from Main.java:390:in `doRunFromMain'
    from Main.java:279:in `internalRun'
    from Main.java:221:in `run'
    from Main.java:201:in `main'
Caused by:
URLClassLoader.java:202:in `run': java.lang.ClassNotFoundException: org.jruby.util.unsafe.UnsafeHolder
    from AccessController.java:-2:in `doPrivileged'
    from URLClassLoader.java:190:in `findClass'
    from JRubyClassLoader.java:92:in `findClass'
    from ClassLoader.java:306:in `loadClass'
    from ClassLoader.java:247:in `loadClass'
    from AtomicReferenceLibrary.java:70:in `<clinit>'
    from AtomicReferenceLibrary.java:51:in `allocate'
    from RubyClass.java:224:in `allocate'
    from RubyClass.java:854:in `newInstance'
    from RubyClass$INVOKER$i$newInstance.gen:-1:in `call'
    from JavaMethod.java:278:in `call'
    from CachingCallSite.java:326:in `cacheAndCall'
    from CachingCallSite.java:170:in `call'
    from foo.rb:6:in `__file__'
    from foo.rb:-1:in `load'
    from Ruby.java:810:in `runScript'
    from Ruby.java:803:in `runScript'
    from Ruby.java:674:in `runNormally'
    from Ruby.java:523:in `runFromMain'
    from Main.java:390:in `doRunFromMain'
    from Main.java:279:in `internalRun'
    from Main.java:221:in `run'
    from Main.java:201:in `main'
```

The workaround is to downgrade `atomic` to `1.0.2` when using `jruby` <= `1.7.2` or to upgrade jruby to >= `1.7.3`.

Any thoughts?

**Comment by headius** [comment]
Fixed by the referenced commit.

**Comment by splattael** [comment]
Thank you! :)
