### ISSUE TITLE
failed compile with atomic-1.1.14.gem

### ISSUE THREAD

**Issue by waldy45** [headius/ruby-atomic#32]
HI I'm getting a fail on compile with atomic-1.1.14.gem when installing rails with the following output. Im using Windows 7 32bit client & ruby 2.0.0-p247

versions:
atomic-1.1.14.gem 
ruby 2.0.0-p247
devkit DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe

Q:\Ruby200\bin>gem install rails
Fetching: i18n-0.6.5.gem (100%)
Successfully installed i18n-0.6.5
Fetching: multi_json-1.8.0.gem (100%)
Successfully installed multi_json-1.8.0
Fetching: tzinfo-0.3.37.gem (100%)
Successfully installed tzinfo-0.3.37
Fetching: atomic-1.1.14.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions. This could take a while...
ERROR: Error installing rails:
ERROR: Failed to build gem native extension.

Q:/Ruby200/bin/ruby.exe extconf.rb
creating Makefile

make "DESTDIR="
generating atomic_reference-i386-mingw32.def
compiling atomic_reference.c
atomic_reference.c: In function 'ir_compare_and_set':
atomic_reference.c:75:2: error: #error No CAS operation available for this platf
orm
make: **\* [atomic_reference.o] Error 1

Gem files will remain installed in Q:/Ruby200/lib/ruby/gems/2.0.0/gems/atomic-1.
1.14 for inspection.
Results logged to Q:/Ruby200/lib/ruby/gems/2.0.0/gems/atomic-1.1.14/ext/gem_make
.out

Q:\Ruby200\bin>

**Comment by sunaku** [comment]
:+1: I'm hitting the same problem on CentOS 5.6 running 64-bit Linux 2.6.18-348.2.1.el5. :sweat:

``` sh
$ gem install atomic -v '1.1.14'
Building native extensions.  This could take a while...
ERROR:  Error installing atomic:
        ERROR: Failed to build gem native extension.

    /ruby-2.0.0-p247/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
compiling atomic_reference.c
atomic_reference.c: In function ‘ir_compare_and_set’:
atomic_reference.c:75:2: error: #error No CAS operation available for this platform
Makefile:223: recipe for target 'atomic_reference.o' failed
make: *** [atomic_reference.o] Error 1


Gem files will remain installed in /rubygems/gems/atomic-1.1.14 for inspection.
Results logged to /rubygems/gems/atomic-1.1.14/ext/gem_make.out
exit 1
```

**Comment by sunaku** [comment]
Good news! :sparkles: This gem installs correctly under GCC 4.8.1: :cake:

``` sh
$ env PATH="/gcc-4.8.1/bin:$PATH" gem install atomic -v '1.1.14'
Building native extensions.  This could take a while...
Successfully installed atomic-1.1.14
1 gem installed
```

Previously, I was using GCC 4.7.2 and faced the problem described in this issue.

**Comment by headius** [comment]
I'd be willing to accept additional patches to aid building on older GCC, but for now since this is working I'm going to close it.

**Comment by Professionalusername** [comment]
Have you found any solutions to the problem in Windows 7, 32 bit?  My issue is identical to the OP, except that I'm using ruby 1.9.3.

**Comment by waldy45** [comment]
Hi,  my client dropped his requirement for this,  so I didn't follow up.  hedius managed to install atomic using a later gcc v 4.8.1

**Comment by sixty4bit** [comment]
atomic-1.1.10.gem
ruby 2.0.0-p353
devkit DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe

The fix I found was to add the DevKit\mingw\bin directory to my PATH. This does not normally get added.

**Comment by cesar-valdez** [comment]
I have ubuntu 16.4 I had the same error in my project

my solution is to install ruby, rbenv, bundler finally delete and create Gemfile file:


**first step: install ruby**

**update system**
 

    sudo apt-get update           
    sudo apt-get upgrade


**rbenv**

    sudo apt-get install git-core curl zlib1g-dev build-essential \   
                             libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 \
                             libxml2-dev libxslt1-dev libcurl4-openssl-dev \
                             python-software-properties libffi-dev
        
    
    
        git clone git://github.com/sstephenson/rbenv.git .rbenv
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(rbenv init -)"' >> ~/.bashrc
        exec $SHELL

**ruby-build**

    git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
    echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
    exec $SHELL


**Install Ruby through rbenv:**

    rbenv install 2.2.1
    rbenv global 2.2.1


**Install bundler**

    echo "gem: --no-ri --no-rdoc" > ~/.gemrc
    gem install bundler
    rbenv rehash


**second step: delete and create the Gemfile file**

Search for the Gemfile file in the project, it must be at the root of the project. for more information about Gemfile http://bundler.io/

    cd peatio

with the command ls we can see all the files and folders of the project

    ls

delete Gemfile file

    rm Gemfile

create Gemfile

    bundle init

now we can install bundle

    bundle install

**Comment by headius** [comment]
Old bugs never die!

@cesar-valdez Perhaps there's something we can do to our Makefile to fix this? Your fix confuses me a bit! 😄
